### ISSUE TITLE
Formula "normalization"

### ISSUE THREAD

**Issue by mauro-milella** [aclai-lab/SoleLogics.jl#1]
Currently, `fnormalize!` is not always capable of collapsing two or more formulas into one unique representation.
E.g "(b∧a)∨(d∧c)" and "(d∧c)∨(a∧b)" are rearranged into, respectively, "(a∧b)∨(c∧d)" and "(c∧d)∨(a∧b)"; instead, both should collapse to the former string representation.

**Comment by giopaglia** [comment]
Is this done?

**Comment by mauro-milella** [comment]
Yep, but now it is renamed to `normalize`. 
I already added the test proposed in the initial comment, this can be closed.
